apiVersion: v1
kind: Service
metadata:
  name: modulo-p-service
  namespace: projeto-distribuido
spec:
  selector:
    app: modulo-p
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort # Expõe o serviço para fora do cluster