apiVersion: apps/v1
kind: Deployment
metadata:
  name: modulo-b-deployment
  namespace: projeto-distribuido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modulo-b
  template:
    metadata:
      labels:
        app: modulo-b
    spec:
      containers:
      - name: modulo-b-container
        image: modulo-b-grpc:latest
        ports:
        - containerPort: 50052
        imagePullPolicy: IfNotPresent